# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list:               $/koderhut/templatetokens/models/token/columns.yaml

# Model Class name
modelClass:         KoderHut\TemplateTokens\Models\Token

# List Title
title:              koderhut.templatetokens::lang.fields.list_page_title.label

# Link URL for each record
recordOnClick:      $.templateTokens.updateToken(":token_name")

# Message to display if the list is empty
noRecordsMessage:   backend::lang.list.no_records

# Records to display per page
recordsPerPage:     30

# Displays the list column set up button
showSetup:          true

# Displays the sorting link on each column
showSorting:        true

# Display checkboxes next to each record
showCheckboxes:     true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons:        list_toolbar

    # Search widget configuration
    search:
        prompt:     backend::lang.list.search_prompt
